# Generated by Django 4.2.5 on 2023-11-28 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0002_alter_customuser_fecha_nacimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, null=True)),
                ('primer_apellido', models.CharField(max_length=255, null=True)),
                ('segundo_apelido', models.CharField(max_length=255, null=True)),
                ('correo_electronico', models.CharField(max_length=255, null=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_taller', models.CharField(max_length=255, null=True)),
                ('seccion', models.CharField(max_length=255, null=True)),
                ('dia_taller', models.CharField(max_length=255, null=True)),
                ('horario', models.TimeField(null=True)),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='talleres.instructor')),
            ],
        ),
    ]
