# Generated by Django 4.2.5 on 2023-11-28 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0003_instructor_taller'),
    ]

    operations = [
        migrations.AddField(
            model_name='taller',
            name='inscripcion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
