# Generated by Django 4.2.5 on 2023-11-28 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0004_taller_inscripcion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Instructor',
            new_name='Instructores',
        ),
        migrations.RenameModel(
            old_name='Taller',
            new_name='Talleres',
        ),
    ]
