# Generated by Django 4.2.5 on 2023-11-28 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0005_rename_instructor_instructores_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Instructores',
            new_name='Instructore',
        ),
        migrations.RenameModel(
            old_name='Talleres',
            new_name='Tallere',
        ),
    ]
