# Generated by Django 4.2.5 on 2023-11-28 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0008_remove_tallere_dia_taller_tallere_jueves_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructore',
            old_name='primer_apellido',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='instructore',
            old_name='segundo_apelido',
            new_name='direccion',
        ),
        migrations.AddField(
            model_name='instructore',
            name='genero',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='instructore',
            name='telefono_contacto',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='instructore',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
