# Generated by Django 4.2.5 on 2023-11-28 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0009_rename_primer_apellido_instructore_apellido_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tallere',
            old_name='horario',
            new_name='horario_inicio',
        ),
        migrations.AddField(
            model_name='tallere',
            name='horario_termino',
            field=models.TimeField(null=True),
        ),
    ]
