# Generated by Django 4.2.5 on 2023-11-29 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0010_rename_horario_tallere_horario_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='talleres_inscritos',
            field=models.ManyToManyField(related_name='usuarios_inscritos', to='talleres.tallere'),
        ),
    ]
